"""
Authentication utilities
"""

from fastapi import Depends, HTTPException, status, Query
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from sqlalchemy.orm import Session
from jose import JWTError, jwt
import logging
from typing import Optional
import uuid

from app.config import settings
from app.database import get_db
from app.models import User

logger = logging.getLogger(__name__)
security = HTTPBearer(auto_error=False)  # Don't auto-error so we can try dev bypass


async def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
    db: Session = Depends(get_db)
) -> User:
    """
    Get current user from JWT token
    """
    try:
        token = credentials.credentials

        # Decode JWT
        payload = jwt.decode(
            token,
            settings.JWT_SECRET_KEY,
            algorithms=[settings.JWT_ALGORITHM]
        )

        user_id = payload.get("sub")
        if not user_id:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid authentication credentials"
            )

        # Get user from database
        user = db.query(User).filter(User.id == user_id).first()

        if not user or not user.is_active:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="User not found or inactive"
            )

        return user

    except JWTError as e:
        logger.error(f"JWT validation error: {e}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials"
        )
    except Exception as e:
        logger.error(f"Authentication error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication failed"
        )


def require_role(*allowed_roles):
    """
    Dependency to require specific user roles
    Usage: current_user: User = Depends(require_role("admin", "moderator"))
    """
    async def role_checker(current_user: User = Depends(get_current_user)) -> User:
        if current_user.role not in allowed_roles:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Access denied. Required roles: {', '.join(allowed_roles)}"
            )
        return current_user

    return role_checker


def extract_phone_from_test_uuid(user_uuid: uuid.UUID) -> str:
    """
    Extract phone number from test UUID generated by mobile app.

    Mobile app generates UUID from phone using this pattern:
    Phone: 8158965836 -> UUID: 81589658-3600-4000-8815-000000000000

    Format breakdown:
    - First segment (8 chars): first 8 digits of phone
    - Second segment (4 chars): last 2 digits + "00"
    - Third segment: always "4000"
    - Fourth segment: "8" + first 3 digits
    - Fifth segment: 12 zeros

    Returns: +91XXXXXXXXXX format phone number
    """
    uuid_str = str(user_uuid)
    parts = uuid_str.split('-')

    if len(parts) != 5:
        # Not a test UUID, return generic phone
        return f"+91{uuid_str.replace('-', '')[:10]}"

    try:
        # Extract first 8 digits from first segment
        first_eight = parts[0]  # e.g., "81589658"

        # Extract last 2 digits from second segment (remove the "00" suffix)
        last_two = parts[1][:2]  # e.g., "3600" -> "36"

        # Combine to get 10-digit phone number
        phone_digits = first_eight + last_two  # e.g., "8158965836"

        return f"+91{phone_digits}"
    except (IndexError, ValueError):
        # Fallback if UUID format doesn't match expected pattern
        return f"+91{uuid_str.replace('-', '')[:10]}"


async def get_current_user_or_dev(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
    dev_user_id: Optional[str] = Query(default=None, description="Development bypass: user ID"),
    db: Session = Depends(get_db)
) -> User:
    """
    Get current user from JWT token OR use dev_user_id query param for development.

    DEV ONLY: Pass ?dev_user_id=<uuid> to bypass authentication.
    Production should use proper JWT tokens only.

    SECURITY FIX: Dev mode is now BLOCKED in production environment.
    """
    # SECURITY FIX: Block dev bypass in production
    if dev_user_id and settings.is_production:
        logger.error(
            f"🚨 SECURITY ALERT: Dev bypass attempted in PRODUCTION! "
            f"User ID: {dev_user_id}"
        )
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                "Development authentication bypass is disabled in production. "
                "Please use proper JWT authentication."
            )
        )

    # Development bypass: if dev_user_id is provided, use it (dev mode only)
    if dev_user_id:
        logger.warning(f"⚠️  DEV BYPASS: Using dev_user_id={dev_user_id} (DO NOT USE IN PRODUCTION)")
        try:
            user_uuid = uuid.UUID(dev_user_id)
            user = db.query(User).filter(User.id == user_uuid).first()

            # Auto-create test user if doesn't exist (DEV MODE ONLY)
            if not user:
                logger.info(f"Creating test user with ID: {dev_user_id}")

                # Extract actual phone number from UUID pattern
                phone_number = extract_phone_from_test_uuid(user_uuid)

                # Generate dummy email from UUID (required by database NOT NULL constraint)
                dummy_email = f"test-{str(user_uuid)[:8]}@boloo-test.local"

                user = User(
                    id=user_uuid,
                    email=dummy_email,  # Required field - generate unique dummy email
                    phone=phone_number,  # Extract phone from UUID pattern
                    name="Test User",
                    role="citizen",
                    is_active=True
                )
                db.add(user)
                db.commit()
                db.refresh(user)
                logger.info(f"Test user created successfully: {dev_user_id} with phone {phone_number} and email {dummy_email}")

            if not user.is_active:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail=f"User {dev_user_id} is inactive"
                )

            return user

        except ValueError:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid user ID format: {dev_user_id}"
            )

    # Normal JWT authentication
    if not credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required. Provide Bearer token or dev_user_id query param."
        )

    return await get_current_user(credentials, db)


# Convenience function for admin-only endpoints
get_current_admin_user = require_role("admin")
